virtualmuseum/__init__.py
# __init__.py
# Virtual Museum

# Flask Imports
from flask import Flask
# Imports
import os

# Create flask application object.
app = Flask(__name__)

# Load configuration.
CONFIGURATION_FILE = os.path.abspath('virtual_museum.conf')
try:
    app.config.from_pyfile(CONFIGURATION_FILE, silent=False)
except IOError:
    # Failed to load from the CONFIGURATION_FILE.
    print(' * Failed to load configuration from %s' %CONFIGURATION_FILE)
except Exception as e:
    print(' * Failed to load configuration file, unknown error: %s' %e)

# Import Blueprints
from virtualmuseum.home.views import home_blueprint
from virtualmuseum.api.views import api_blueprint

# Register Blueprints
app.register_blueprint(home_blueprint)
app.register_blueprint(api_blueprint, url_prefix='/api/v1.0')

virtualmuseum/api/views.py
# views.py
# Virtual Museum
# Views for the api blueprint.

# Flask Imports
from flask import Blueprint
from flask import jsonify
from flask import request
# Application Imports
from virtualmuseum import app
# Imports
import requests

api_blueprint = Blueprint('api', __name__)

@api_blueprint.route('/museum')
@api_blueprint.route('/museum/search/<string:search>')
@api_blueprint.route('/museum/<int:page_number>')
def index(search=None, page_number=1):
    """
    API Index.
    """
    
    # http://www.vam.ac.uk/api/json/museumobject
    url = app.config['MUSEUM_API_ENDPOINT'] + "?limit=20" 
    if search:
        url = app.config['MUSEUM_API_ENDPOINT'] + '/search?limit=20&q='+search.replace(" ","+")
    # Calculate offset.
    offset = (page_number - 1) * 20
    url = url + "&offset=%d" %offset
    # Get the data from the api. 
    response = requests.get(url).json()
    # Add the IMAGE URIs to the response.
    for record in response["records"]:
        # Add a new field for the image_uri.
        record["fields"]["image_uri"] = app.config['MUSEUM_IMAGE_ENDPOINT']+record["fields"]["primary_image_id"][:6]+'/'+record["fields"]["primary_image_id"]+'_jpg_w.jpg'

    return jsonify(response)

virtualmuseum/home/views.py
# views.py
# Virtual Museum
# Views for the home blueprint.

# Flask Imports
from flask import Blueprint
from flask import render_template
from flask import request

home_blueprint = Blueprint('home', __name__)

@home_blueprint.route('/')
def index():
    """
    Application index.
    """
    # Search variable.
    search = None
    
    # Get http type args.
    if request.args.get("search"):
        search = request.args.get("search")
    
    return render_template('home/index.html', search=search)
    
@home_blueprint.route('/view')
def view():
    """
    View images.
    """
    
    return render_template('home/view.html')

virtualmuseum/templates/_layout.html
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Virtual Museum{% endblock %}</title>
        
        <!-- Bootstrap -->
        <link rel="icon" type="img/ico" href="{{url_for('static', filename='favicon.ico')}}">
        <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
        {% block style %}{% endblock %}
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
        <script src="{{url_for('static', filename='js/three.min.js')}}"></script>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!-- Content -->
        {% block content %}{% endblock %}
        <!-- Javascript -->
        {% block script %}{% endblock %}
    </body>
</html>

virtualmuseum/templates/home/index.html
{% extends '_layout.html' %}
{% block style %}
<!-- Styles -->
<link href="{{url_for('static', filename='css/style.css')}}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div id="landing">
        <div class=".container">
            <div class="box">
                <img class="logo" src='/static/va.png'>
                <h2>Victoria & Albert Museum Tour</h2>
                <hr>
                <h2>The World's Leading Museum of Art and Design</h2>
                <form method="GET" action="">
                    <div class="row">
                        <div class="col-md-4 col-md-offset-4">
                            <div class="input-group">
                                <input type="text" name="search" class="form-control search" placeholder="{% if search %}{{search}}{%else%}Search for...{% endif %}">
                                <span class="input-group-btn">
                                    <input class="btn btn-default" type="submit" value="Go">
                                </span>
                            </div>
                            
                            <p id="error" style="display:none;margin-top:20px;">API Error: could not get data from the API. Please refresh the page.</p>
                        </div>
                    </div>
                </form>
                <button id="im_feeling_lucky" class="btn btn-default" type="button">{% if search %}Look for "{{search}}" in the museum{%else%}I'm feeling lucky{% endif %}</button>
            </div>
        </div>
    </div>
    <div id="blocker">
        <div id="instructions">
            <div class=".container">
                <img class="logo" src='/static/va.png'>
                <h2>Victoria & Albert Museum Tour</h2>
                <hr>
                <h2>The World's Leading Museum of Art and Design</h2>
                <button id="continue_button" class="btn btn-default" type="button">Continue looking around</button>
                <a role="button" href="{{url_for('home.index')}}" class="btn btn-default">Take me home</a>
            </div>
        </div>
    </div>
    <div id="information"></div>
{% endblock %}
{% block script %}
    <!-- javascript -->
    <script src="{{url_for('static', filename='js/PointerLockControls.js')}}"></script>
    <script src="{{url_for('static', filename='js/basic_museum_scene.js')}}"></script>
    <script type="text/javascript">
        var cube_start_position = -40;
        
        // Call the Init Function.
        init();
        
        $.get({% if search %}"/api/v1.0/museum/search/{{search}}"{% else %}"/api/v1.0/museum"{% endif %}).done(function(resultData) {
            document.getElementById('error').style.display = "none";
            document.getElementById('im_feeling_lucky').style.display = "inline-block";
            data = resultData.records
            start = 1;
            
            for(var i=0;i<data.length;i+=2){
                x_pos = 40 * start + (Math.floor(Math.random()*31) - 10);
                start = start*-1;
                z_pos = (i * -10) + cube_start_position
                // Add the stand.
                addStand(
                    [
                    data[i].fields,
                    data[i+1].fields,
                    ], x_pos, 0, z_pos
                );
            }
            cube_start_position = (i * -20) + cube_start_position;
        
        }).fail(function (resultData){
            console.log("API Error");
            document.getElementById('error').style.display = "block";
            document.getElementById('im_feeling_lucky').style.display = "none";
        });
        
        // Render the page.
        render();
    </script>
{% endblock %}

virtualmuseum/templates/home/view.html
{% extends '_layout.html' %}
{% block content %}
    <style type="text/css" media="all">
    @import url(https://fonts.googleapis.com/css?family=Indie+Flower);
    body {
        font-family: 'Indie Flower', cursive;
    }
    .image {
        display: block;
        overflow: hidden;
        background-size: cover;
        background-position: center top;
        background-repeat: no-repeat;
        width: 33%;
        height: 200px;
        float: left;
    }
    #load_more {
        position: fixed;
        bottom: 10px;
        left: 10px;
    }
    </style>
    <div id="gallery">
    </div>
    <button type="button" class="btn btn-primary" id="load_more">Load more</button>
{% endblock %}
{% block script %}
    <script>
        // Variable to keep track of the next page.
        var next_page = 2;
        // HTML Load Function
        function load_images(page_number){
            $.ajax({
                url: "/api/v1.0/museum/"+ page_number,
                type: "GET",
        
                contentType: 'application/json; charset=utf-8',
                success: function(resultData) {
                    data = resultData.records
                    for(var i=0;i<data.length;i++){
                        html = '<a href="'+data[i].fields.image_uri+'" class="image" style="background-image: url('+data[i].fields.image_uri+');"></a>'
                        $("#gallery").append(html);
                    }
                },
                error : function(jqXHR, textStatus, errorThrown) {
                },
        
                timeout: 600,
            });
        }
        $('#load_more').click(function(event) {
            load_images(next_page);
            next_page ++;
        });
        load_images(1);
    </script>
{% endblock %}